# Generated by Django 6.1 on 2026-08-10 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 10, 17, 21, 17, 710359, tzinfo=datetime.timezone.utc)),
        ),
    ]
