# Generated by Django 6.1 on 2026-08-12 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 12, 17, 52, 18, 839090, tzinfo=datetime.timezone.utc)),
        ),
    ]
