# Generated by Django 6.1 on 2026-08-16 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 16, 7, 53, 14, 128292, tzinfo=datetime.timezone.utc)),
        ),
    ]
